"""
This type stub file was generated by pyright.
"""

from .amadeus import Client
from .version import version
from .client.location import Location
from .client.hotel import Hotel
from .client.direction import Direction
from .client.request import Request
from .client.response import Response
from .client.errors import AuthenticationError, ClientError, NetworkError, NotFoundError, ParserError, ResponseError, ServerError

__all__ = ['Client', 'Location', 'Direction', 'version', 'ResponseError', 'ParserError', 'ServerError', 'AuthenticationError', 'NotFoundError', 'ClientError', 'Request', 'Response', 'NetworkError', 'Hotel']
