"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class FlightAvailabilities(Decorator):
    def post(self, body):
        '''
        Get available seats in different fare classes

        .. code-block:: python

            amadeus.shopping.availability.flight_availabilities.post(body)

        :param body: the parameters to send to the API

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


