"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class FlightOrders(Decorator):
    def post(self, flight, travelers):
        '''
        Books a flight

        .. code-block:: python

            amadeus.booking.flight_orders.post(flight, travelers)

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


