"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class FlightOrder(Decorator):
    def __init__(self, client, flight_order_id) -> None:
        ...
    
    def get(self, **params):
        '''
        Retrieves a flight order based on its ID.

        .. code-block:: python

            amadeus.booking.flight_order('eJzTd9f3NjIJdzUGAAp%2fAiY=').get()

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    
    def delete(self, **params):
        '''
        Deletes a flight order based on its ID.

        .. code-block:: python

            amadeus.booking.flight_order('eJzTd9f3NjIJdzUGAAp%2fAiY=').delete()

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


