"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class HotelOrders(Decorator):
    def post(self, guests, travel_agent, room_associations=..., payment=..., arrival_information=...):
        '''
        Book hotel(s) via Hotel Booking API V2

        .. code-block:: python

            amadeus.booking.hotel_orders.post(guests,
                                              travel_agent,
                                              room_associations,
                                              payment,
                                              arrival_information)

        The parameters guests and room_associations can be passed as dictionary
        or list of dictionaries. If they are dictionary in this method they are
        converted to a list of dictionaries.

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


