"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class HotelBookings(Decorator):
    def post(self, hotel_offer_id, guests, payments):
        '''
        Books a hotel

        .. code-block:: python

            amadeus.booking.hotel_bookings.post(hotel_offer_id, guests, payments)

        The parameters guests and payments can be passed as dictionary
        or list of dictionaries. If they are dictionary in this method they are
        converted to a list of dictionaries.

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


