"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Booking(Decorator):
    def __init__(self, client) -> None:
        ...
    
    def flight_order(self, flight_order_id): # -> FlightOrder:
        ...
    


__all__ = ['FlightOrders', 'FlightOrder', 'HotelBookings', 'HotelOrders']
