"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Ordering(Decorator):
    def __init__(self, client) -> None:
        ...
    
    def transfer_order(self, order_id): # -> TransferOrder:
        ...
    


__all__ = ['TransferOrders', 'TransferOrder']
