"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class ReferenceData(Decorator):
    def __init__(self, client) -> None:
        ...
    
    def location(self, location_id): # -> Location:
        ...
    


