"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Shopping(Decorator):
    def __init__(self, client) -> None:
        ...
    
    def hotel_offer_search(self, offer_id): # -> HotelOfferSearch:
        ...
    
    def activity(self, activity_id): # -> Activity:
        ...
    


__all__ = ['FlightDates', 'FlightDestinations', 'FlightOffers', 'FlightOffersSearch', 'Availability']
