"""
This type stub file was generated by pyright.
"""

class Pagination:
    def previous(self, response): # -> None:
        ...
    
    def next(self, response): # -> None:
        ...
    
    def first(self, response): # -> None:
        ...
    
    def last(self, response): # -> None:
        ...
    


