"""
This type stub file was generated by pyright.
"""

class Parser:
    @staticmethod
    def error_for(status_code, parsed): # -> type[NetworkError] | type[ServerError] | type[AuthenticationError] | type[NotFoundError] | type[ClientError] | type[ParserError] | None:
        ...
    


