"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class ByHotels(Decorator):
    def get(self, **params):
        '''
        Searches for hotel using it's unique id.

        .. code-block:: python


            amadeus.reference_data.locations.hotels.by_hotels.get(
                hotelIds=["ADPAR001"])

        :param hotelIds: Amadeus Property Codes (8 chars)
            For example: ``["ADPAR001"]``

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


