"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Location(Decorator):
    def __init__(self, client, location_id) -> None:
        ...
    
    def get(self, **params):
        '''
        Returns details for a specific airport.

        .. code-block:: python

            amadeus.reference_data.location('ALHR').get()

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


