"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class RecommendedLocations(Decorator):
    def __init__(self, client) -> None:
        ...
    
    def get(self, **params):
        '''
        Returns a list of destination recommendations

        .. code-block:: python


            client.reference_data.recommended_locations.get(
                cityCodes='PAR'
                travelerCountryCode='FR'
            )

        :param cityCodes: city used by the algorithm to recommend new destinations
            For example: ``PAR``
        :param travelerCountryCode: origin country following IATA standard
            For example: ``FR``

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


