"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class TransferOrders(Decorator):
    def post(self, body, **params):
        '''
        Performs the final booking for a chosen transfer

        .. code-block:: python

            amadeus.ordering.transfer_orders.post(body, offerId=offer_id)

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


