"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class TransferOrder(Decorator):
    def __init__(self, client, order_id) -> None:
        ...
    


