"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Destinations(Decorator):
    def get(self, **params):
        '''
        Get airline destinations.

        .. code-block:: python

            amadeus.airline.destinations.get(airlineCode='BA')

        :param airlineCode: the airline code following IATA standard.
            Example: ``"BA"``

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


