"""
This type stub file was generated by pyright.
"""

class ResponseError(RuntimeError):
    '''
    An Amadeus error

    :var response: The response object containing the raw HTTP response and
        the request used to make the API call.
    :vartype response: amadeus.Response

    :var code: A unique code for this type of error. Options include
        ``NetworkError``, ``ParserError``, ``ServerError``,
        ``AuthenticationError``, ``NotFoundError`` and ``UnknownError``.
    :vartype code: str
    '''
    def __init__(self, response) -> None:
        ...
    
    def description(self): # -> str:
        ...
    
    @staticmethod
    def short_description(response): # -> str:
        ...
    
    def long_description(self, response): # -> str:
        ...
    
    @staticmethod
    def error_description(response): # -> str:
        ...
    
    def errors_descriptions(self, response): # -> str:
        ...
    
    @staticmethod
    def errors_description(error): # -> str:
        ...
    


class NetworkError(ResponseError):
    '''
    This error occurs when there is some kind of error in the network
    '''
    ...


class ParserError(ResponseError):
    '''
    This error occurs when the response type was JSOn but could not be parsed
    '''
    ...


class ServerError(ResponseError):
    '''
    This error occurs when there is an error on the server
    '''
    ...


class ClientError(ResponseError):
    '''
    This error occurs when the client did not provide the right parameters
    '''
    ...


class AuthenticationError(ResponseError):
    '''
    This error occurs when the client did not provide the right credentials
    '''
    ...


class NotFoundError(ResponseError):
    '''
    This error occurs when the path could not be found
    '''
    ...


