"""
This type stub file was generated by pyright.
"""

class Location:
    '''
    A list of location types, as used in searching for locations

    .. code-block:: python


        from amadeus import Location

        amadeus.reference_data.locations.get(
            keyword='lon',
            subType=Location.ANY
        )

    :cvar AIRPORT: ``"AIRPORT"``
    :cvar CITY: ``"CITY"``
    :cvar ANY: ``"AIRPORT,CITY"``
    '''
    AIRPORT = ...
    CITY = ...
    ANY = ...


