"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Activity(Decorator):
    def __init__(self, client, activity_id) -> None:
        ...
    
    def get(self, **params):
        '''
        Returns a single activity from a given id.

        .. code-block:: python

            client.shopping.activities('4615').get()

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


