"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Activities(Decorator):
    def __init__(self, client) -> None:
        ...
    
    def get(self, **params):
        '''
        Returns activities for a given location

        .. code-block:: python


            client.shopping.activities.get(
                longitude=2.160873,
                latitude=41.397158
            )

        :param latitude: latitude of geographic location to search around.
            For example: ``41.397158``
        :param longitude: longitude of geographic location to search around.
            For example: ``2.160873``

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


