"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class HotelOfferSearch(Decorator):
    def __init__(self, client, offer_id) -> None:
        ...
    
    def get(self, **params):
        '''
        Returns details for a specific offer

        .. code-block:: python

            amadeus.shopping.hotel_offer_search('XXX').get

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


