"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class TransferOffers(Decorator):
    def post(self, body):
        '''
        Get transfer offers

        .. code-block:: python

            amadeus.shopping.transfer_offers.post(body)

        :param body: the parameters to send to the API

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


