"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class FlightOffersPrice(Decorator):
    def post(self, body, **params):
        '''
        Gets a confirmed price and availability of a flight

        .. code-block:: python

            amadeus.shopping.flight_offers.pricing.post(body, params)

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


