"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Upselling(Decorator):
    def post(self, body):
        '''
        Get flight offers with branded fares

        .. code-block:: python

            amadeus.shopping.flight_offers.upselling.post(body)

        :param body: the parameters to send to the API

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


