"""
This type stub file was generated by pyright.
"""

from amadeus.client.decorator import Decorator

class Cancellation(Decorator):
    def __init__(self, client, order_id) -> None:
        ...
    
    def post(self, body, **params):
        '''
        Cancels a transfer reservation

        .. code-block:: python

            amadeus.ordering.transfer_order(order_id).transfers.cancellation.post(body,
            confirmNbr=confirm_nbr)

        :rtype: amadeus.Response
        :raises amadeus.ResponseError: if the request could not be completed
        '''
        ...
    


